### ISSUE TITLE
Не загружает аву

### ISSUE THREAD

**Issue by EmpathyZ** [pozhiloy-enotik/zoom-gta#1]
Все сделал, модули установил. Ниже лог будет. ( 100% пропуск кадров ;D )
If you like this program, please, consider donating:
https://donatepay.ru/don/pozhiloyenotik
https://www.donationalerts.com/r/pozhiloyenotik
Enter your e-mail:
*************
Enter your password:
**************
Processing...
Enter the name of a .gif:
examples/krutilka
Uploading
{"status":true,"errorCode":0,"errorMessage":null,"result":"https://us04images.zoom.us/p/XBm49eEXT4eLt4PpnI5NLA/5bf50f22-548d-4fdf-9212-242de2586540?type=tmp"}
{"status":true,"errorCode":0,"errorMessage":null,"result":"https://us04images.zoom.us/p/XBm49eEXT4eLt4PpnI5NLA/5706006a-cc8d-4b26-a85b-bc88388adebf?type=tmp"}
{"status":true,"errorCode":0,"errorMessage":null,"result":"https://us04images.zoom.us/p/XBm49eEXT4eLt4PpnI5NLA/18f2cc82-cd92-4825-8350-a026d3a7f89d?type=tmp"}
{"status":true,"errorCode":0,"errorMessage":null,"result":"https://us04images.zoom.us/p/XBm49eEXT4eLt4PpnI5NLA/e4511eac-40fb-4ec2-b927-74e57c97931f?type=tmp"}
{"status":true,"errorCode":0,"errorMessage":null,"result":"https://us04images.zoom.us/p/XBm49eEXT4eLt4PpnI5NLA/cab34338-1cd3-4c54-8f10-a386ca82c43d?type=tmp"}
{"status":true,"errorCode":0,"errorMessage":null,"result":"https://us04images.zoom.us/p/XBm49eEXT4eLt4PpnI5NLA/edf4e3eb-4a4d-4e77-ab3e-0b7389efd025?type=tmp"}
{"status":true,"errorCode":0,"errorMessage":null,"result":"https://us04images.zoom.us/p/XBm49eEXT4eLt4PpnI5NLA/c9041ed5-5407-4cfb-a82f-3a636e0ee3a9?type=tmp"}
{"status":true,"errorCode":0,"errorMessage":null,"result":"https://us04images.zoom.us/p/XBm49eEXT4eLt4PpnI5NLA/4fa7077d-e727-4036-ab38-72387b1bd080?type=tmp"}
{"status":true,"errorCode":0,"errorMessage":null,"result":"https://us04images.zoom.us/p/XBm49eEXT4eLt4PpnI5NLA/bccdb526-cb80-4af8-8aff-e1ce52bb3ca3?type=tmp"}
{"status":true,"errorCode":0,"errorMessage":null,"result":"https://us04images.zoom.us/p/XBm49eEXT4eLt4PpnI5NLA/d6374e81-d4d3-4155-96fe-03d4bfae9495?type=tmp"}
{"status":true,"errorCode":0,"errorMessage":null,"result":"https://us04images.zoom.us/p/XBm49eEXT4eLt4PpnI5NLA/4cd6f932-a94e-4d57-9a70-9c992389268b?type=tmp"}
Enter the delay:
1
Starting... Press Ctrl+C to stop
Frame: 1
Frame: 2
Frame: 3
Frame: 4
Frame: 5
Frame: 6

**Comment by pozhiloy-enotik** [comment]
Обновите программу и попробуйте еще раз

**Comment by EmpathyZ** [comment]
> Обновите программу и попробуйте еще раз

Ворк. Я чекнул версию до этого и она принимала любые данные  от акка, даже если они не верные. Мб в этом трабл был
