### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by FalloutBoyyy** [pozhiloy-enotik/zoom-gta#2]
Ничего не происходит на этапе установки delay.

**Comment by pozhiloy-enotik** [comment]
Обновите программу и попробуйте еще раз. Не забудьте прикрепить лог

**Comment by kanichiwa** [comment]
![image](https://user-images.githubusercontent.com/63748263/79379880-43db6700-7f68-11ea-8f29-4fc986573178.png)
помогите пожалуйста!!!

**Comment by pozhiloy-enotik** [comment]
> ![image](https://user-images.githubusercontent.com/63748263/79379880-43db6700-7f68-11ea-8f29-4fc986573178.png)
> помогите пожалуйста!!!

Здравствуйте, вижу вашу проблему. Пожалуйста, выполните команды из инструкции еще раз по-очередно. Рад был помочь))

**Comment by kanichiwa** [comment]
А не могли бы помочь, что нужно сделать? Плиз

**Comment by pozhiloy-enotik** [comment]
Доброй ночи, в данный момент у вас есть два решения. Давайте я опишу их по-очередно
1. Попробуйте переустановить систему. Если это не поможет, необходимо будет установить Linux с официального сайта.
2. Попробуйте написать 

pip3 install -r requirements.txt 

Если проблема будет решена, дайте знать

**Comment by kanichiwa** [comment]
Еще вопрос, пожалуйста скажите куда кидать гифки, в какую папку?

**Comment by kanichiwa** [comment]
![image](https://user-images.githubusercontent.com/63748263/79382407-1f818980-7f6c-11ea-9807-80ec31d1cfa4.png)

**Comment by pozhiloy-enotik** [comment]
Откройте проводник и перейдите по этому пути 
![Screenshot_120](https://user-images.githubusercontent.com/49619526/79382586-62dbf800-7f6c-11ea-9a09-986d402e5510.png)
Гифки необходимо помещать туда


> 
> 
> Еще вопрос, пожалуйста скажите куда кидать гифки, в какую папку?

**Comment by kanichiwa** [comment]
Все работает, спасибо!

**Comment by kanichiwa** [comment]
![image](https://user-images.githubusercontent.com/63748263/79435210-0adadb00-7fd8-11ea-98ed-4aa276eb1941.png)
гифка идет с задержками, помогите.

**Comment by pozhiloy-enotik** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/63748263/79435210-0adadb00-7fd8-11ea-98ed-4aa276eb1941.png)
> гифка идет с задержками, помогите.

Здравствуйте. К величайшему сожалению, я не могу увидеть на данной фотокарточке проблему. Пожалуйста, распишите ваш вопрос в более подробной форме

**Comment by kanichiwa** [comment]
Очень медленна смена картинок

**Comment by pozhiloy-enotik** [comment]
> 
> 
> Очень медленна смена картинок

Читайте [README](README.md)

**Comment by mtz0-o** [comment]
братик, я вроде всё сделал как в readme сказано, всё равно слишком медленное слайдшоу, можешь поподробней расписать?
