### ISSUE TITLE
Здравствуйте)

### ISSUE THREAD

**Issue by naketu** [pozhiloy-enotik/zoom-gta#3]
Не понимаю, откуда появляется ошибка Invalid parametr user Id, которая приводит к пропуску всех кадров. Если объясните, в чем проблема, буду очень благодарен) 
Выглядит как то так:

Processing...
Enter the name of a .gif:
examples/kamen
Uploading
{"status":true,"errorCode":0,"errorMessage":null,"result":"https://us04images.zoom.us/p/YGhFvZ0CTaCfgtXS-cXHWA/a1ea6c8e-b728-4101-929b-32d69eeb6103?type=tmp"}
{"status":true,"errorCode":0,"errorMessage":null,"result":"https://us04images.zoom.us/p/YGhFvZ0CTaCfgtXS-cXHWA/c2ff4eab-e01e-40d8-98fa-102f46b18b4f?type=tmp"}
{"status":true,"errorCode":0,"errorMessage":null,"result":"https://us04images.zoom.us/p/YGhFvZ0CTaCfgtXS-cXHWA/9bf29343-def9-47a7-aed8-4b5124b7edd6?type=tmp"}
{"status":true,"errorCode":0,"errorMessage":null,"result":"https://us04images.zoom.us/p/YGhFvZ0CTaCfgtXS-cXHWA/b970f48c-355b-4b30-9822-030b760468ea?type=tmp"}
{"status":true,"errorCode":0,"errorMessage":null,"result":"https://us04images.zoom.us/p/YGhFvZ0CTaCfgtXS-cXHWA/3684bc59-9a36-4576-af2a-d4a6f26e339e?type=tmp"}
{"status":true,"errorCode":0,"errorMessage":null,"result":"https://us04images.zoom.us/p/YGhFvZ0CTaCfgtXS-cXHWA/47d8d100-e26e-4e17-b02e-ff9e7a81db6d?type=tmp"}
{"status":true,"errorCode":0,"errorMessage":null,"result":"https://us04images.zoom.us/p/YGhFvZ0CTaCfgtXS-cXHWA/0d25015e-ccbc-4721-9dc0-3d8da41339f3?type=tmp"}
{"status":true,"errorCode":0,"errorMessage":null,"result":"https://us04images.zoom.us/p/YGhFvZ0CTaCfgtXS-cXHWA/dc5092fa-11de-41d5-98d9-7d404151e062?type=tmp"}
{"status":true,"errorCode":0,"errorMessage":null,"result":"https://us04images.zoom.us/p/YGhFvZ0CTaCfgtXS-cXHWA/e60e2ce6-65de-47f4-a4d2-dfc8f650ddfe?type=tmp"}
{"status":true,"errorCode":0,"errorMessage":null,"result":"https://us04images.zoom.us/p/YGhFvZ0CTaCfgtXS-cXHWA/78276eea-2809-42cc-9d58-191dfaae5a3d?type=tmp"}
{"status":true,"errorCode":0,"errorMessage":null,"result":"https://us04images.zoom.us/p/YGhFvZ0CTaCfgtXS-cXHWA/3b709d66-2d9b-40cc-8021-5df6332a8c59?type=tmp"}
{"status":true,"errorCode":0,"errorMessage":null,"result":"https://us04images.zoom.us/p/YGhFvZ0CTaCfgtXS-cXHWA/04edf65b-1739-4881-b97a-e437b2f50d32?type=tmp"}
{"status":true,"errorCode":0,"errorMessage":null,"result":"https://us04images.zoom.us/p/YGhFvZ0CTaCfgtXS-cXHWA/9095a0ae-f4a4-4687-9b8a-9daa21e391bc?type=tmp"}
{"status":true,"errorCode":0,"errorMessage":null,"result":"https://us04images.zoom.us/p/YGhFvZ0CTaCfgtXS-cXHWA/1e3b9dff-9786-4310-b420-6e561a57865a?type=tmp"}
{"status":true,"errorCode":0,"errorMessage":null,"result":"https://us04images.zoom.us/p/YGhFvZ0CTaCfgtXS-cXHWA/ca162ffc-4403-428a-811a-7150f0611728?type=tmp"}
Enter the delay:
1
Starting... Press Ctrl+C to stop
Frame 1 skipped. An error occurred: "Invalid parameter userId."
Frame 2 skipped. An error occurred: "Invalid parameter userId."
Frame 3 skipped. An error occurred: "Invalid parameter userId."
Frame 4 skipped. An error occurred: "Invalid parameter userId."

**Comment by pozhiloy-enotik** [comment]
В процессе исправления

**Comment by pozhiloy-enotik** [comment]
Просьба проверить

**Comment by naketu** [comment]
угу
сейчас

**Comment by naketu** [comment]
Оооооооо даааааа
Работает
Автор крут)
Спасибо большое))))
