### ISSUE TITLE
Проблемы с воспроизведением

### ISSUE THREAD

**Issue by Herpo** [pozhiloy-enotik/zoom-gta#4]
Слепил я вот такую незамысловатую штуку, как говорится, на коленке, но мне нравится))
![9](https://user-images.githubusercontent.com/63284142/79133375-970cb880-7db4-11ea-9316-81ebc23c4783.gif)
Всё идёт прекрасно, но только до того момента, как начинается воспроизведение. Почему-то первый кадр норм, второй с ухудшенным качеством, а потом идут кадры с ухудшенным качеством и  инвертированными цветами (как в режиме негатив), после середины всё в обратном порядке. Пробовал с другими гифками, в том числе и с примерами, там всё было норм. 
P.S. Я на Termux, дополнительную штуку под него ввёл, хотя без неё было то же самое, обновил даже. Тема годная, хочется пользоваться)

**Comment by pozhiloy-enotik** [comment]
Здравствуйте. Проблема должна быть решена:
- Был изменен метод разбивки .gif на кадры
- На всякий случай обновлен README
Просьба обновить репозиторий и сообщить результат

**Comment by Herpo** [comment]
Браво, маэстро! Аплодирую стоя. Всё работает как часы. А если уж гифка понравилась, то, конечно, забирайте) 
Удачи!

**Comment by pozhiloy-enotik** [comment]
Спасибо)
