### ISSUE TITLE
Проблема с установкой

### ISSUE THREAD

**Issue by Pilmesha** [pozhiloy-enotik/zoom-gta#6]
Я ввожу в консоль первую команду, но мне пишет что такой команды нет.
![image](https://user-images.githubusercontent.com/64522023/80571072-01586680-8a0d-11ea-8e11-6bff1f1a44e7.png)

Подскажите пожайлуста что делать.

**Comment by pozhiloy-enotik** [comment]
Здравствуйте, вижу вашу проблему. Пожалуйста, попробуйте прочитать инструкцию еще раз. Если данная ошибка останется, запустите программу в Linux

**Comment by Pilmesha** [comment]
Спасибо, но ещё один вопрос, если я вхожу в зум через фейсбук, то надо вводить пароль от фейсбука или как?

**Comment by pozhiloy-enotik** [comment]
Необходимо создать обычный аккаунт, это не сложно)

**Comment by Pilmesha** [comment]
У меня в начале были сложности с созданием обычного аккаунта(письмо не приходило на почту), поэтому я создала акк через фейсбук. Попробую создать обычный сейчас

**Comment by Pilmesha** [comment]
Спасибо, все получилось
