### ISSUE TITLE
Проблема со входом

### ISSUE THREAD

**Issue by Pilmesha** [pozhiloy-enotik/zoom-gta#7]
Здравствуйте, у меня работала эта программа несколько дней и все было нормально, но сегодня после того как я выбрала свой аккаунт(он был сохранен), мне написало что имейл или пароль неправильные, хотя я ничего не меняла и в сам зум вхожу нормально. Я пыталась переустановить питон и саму программу,но ничего не работает. Можете подсказать,что делать?

**Comment by pozhiloy-enotik** [comment]
Здравствуйте. Да, действительно, теперь при входе требуется ввод капчи. Постараемся пофиксить в течении недели. Ожидайте
![капча](https://user-images.githubusercontent.com/49619526/80952666-b078b180-8e02-11ea-8791-95451caa10c2.jpg)

**Comment by Pilmesha** [comment]
Спасибо,буду ждать

**Comment by pozhiloy-enotik** [comment]
Проблема решена. Просьба проверить

**Comment by Pilmesha** [comment]
Работает. Большое спасибо

ср, 6 Май 2020, 2:54 PM pozhiloy-enotik <notifications@github.com>:
